<?php
  include("componentes/header.php");
  include("componentes/nav.php");
  include("componentes/slider.php");
  include("componentes/cards.php");
  include("componentes/parallax.php");
  include("componentes/video.php");
  include("componentes/footer.php");
?>
